title: Link
handle: link
status: ready
variants:
  - name: yellow
    context:
      text: Search Boston.gov
      url: https://search.boston.gov
      theme: yellow
  - name: white
    context:
      text: Search Boston.gov
      url: https://search.boston.gov
      theme: white
context:
  text: Search Boston.gov
  url: https://search.boston.gov
