title: Section Header
handle: section_header
status: ready
variants:
  - name: Yellow
    context:
      header:
        theme: y
  - name: White
    context:
      header:
        theme: w
  - name: Small
    context:
      header:
        theme: sm
context:
  header:
    title: Transportation Department
    contact:
      title: Public Works
      link: https://www.boston.gov/departments/public-works
