title: 'Web Components: Map'
handle: map
status: ready
notes: |
  {{stencil_readme "map"}}
context: 
  heading: Parking and city councilors
  show_legend: true
  show_instructions: true
  open_overlay: true

variants:
  - name: No Overlay
    context:
      show_address_search: false
      show_legend: false
      show_instructions: false

  - name: Address Search
    context:
      show_address_search: true
      show_instructions: false
      show_legend: false

  - name: Filters
    context:
      show_filters: true
      show_instructions: false

  - name: Cluster Icons
    context:
      cluster_icons: true
      open_overlay: false

  # This is here for the TestCafe tests in order to test opening the modal.
  - name: Modal Closed
    context:
      modal: true
      modal_show_link: true
      show_address_search: true
      modal_hidden: true

