title: Photo
handle: photo
status: ready
variants:
  - name: With Caption
    status: 'wip'
    context:
      has_caption: true
      title: This is the title
      short_title: Love your block
      caption: Here's a caption of the photo
      credit: The Digital Team
context:
  short_title: Love your block
  cta:
    text: Here's a link
    link: https://www.boston.gov
  image:
    wide1x: https://patterns.boston.gov/assets/images/fleet/boston-header3.jpg
    desktop1x: https://patterns.boston.gov/assets/images/fleet/boston-header3.jpg
    tablet1x: https://patterns.boston.gov/assets/images/fleet/boston-header3.jpg
    mobile1x: https://patterns.boston.gov/assets/images/fleet/boston-header3.jpg
