title: Block
handle: block
status: ready
variants:
  - name: grey
    context:
      theme: g
  - name: white
    context:
      theme: w
  - name: charles blue
    context:
      theme: b
      theme_dark: true
  - name: optimistic blue
    context:
      theme: ob
      theme_dark: true
context:
  header:
    title: Transportation Department
